image: ubuntu:20.04

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -yq install git build-essential cmake libmicrohttpd-dev zlib1g-dev
    - git submodule sync --recursive
    - git submodule update --init --recursive
  artifacts:
    untracked: true
  script:
    - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_COVERAGE=ON -DCMAKE_CXX_FLAGS='-O0 -g -pg -fprofile-arcs -ftest-coverage' -DCMAKE_EXE_LINKER_FLAGS=-pg -DCMAKE_SHARED_LINKER_FLAGS=-pg .. && make

coverage:
  stage: test
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -yq install lcov curl libmicrohttpd-dev libssl-dev zlib1g-dev netcat-openbsd ssl-cert
  dependencies:
    - build
  artifacts:
    untracked: true
  script:
    - cd build
    - sh -c './CoverageTest'
    - lcov -d . -c --output-file app-raw.info
    - lcov --remove app-raw.info '/usr/include/*' '*/_deps/*' -o app.info
    - lcov -l app.info
